- hosts: localhost
  connection: local
  become: true

- name: Install Dist Upgrades
  ansible.builtin.package:
    update_cache: true
    upgrade: dist

- name: Install packages
  ansible.builtin.package:
    update_cache: true
    name: "{{ item }}"
    state: latest
    loop_control:
      loop_var: item
    loop: # List of packages to install
      - neofetch
      - wget
      - curl
      - zsh
      - tldr
      - bat
      - zoxide
      - fzf
      - gpg
