- name: Execute ansible_pull_repo against localhost
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories
      ansible.builtin.package:
        update_cache: true
      changed_when: false

  tasks:
    - name: Include dist-upgrade task
      ansible.builtin.include_tasks: tasks/dist-upgrade.yml
    - name: Includes packages task
      ansible.builtin.include_tasks: tasks/packages.yml
