- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories
      ansible.builtin.package:
        update_cache: true
      changed_when: false

  tasks:
    - name: Execute packages task
      ansible.builtin.include_tasks: tasks/packages.yml
