- name: Create ansible-user
  ansible.builtin.user:
    name: ansible-user
    system: true

- name: Copy sudoers_ansible-user
  ansible.builtin.copy:
    src: files/sudoers_ansible-user
    dest: /etc/sudoers.d/ansible-user
    owner: root
    group: root
    mode: "0440"
