- name: Install packages
  ansible.builtin.package:
    update_cache: true
    name: "{{ item }}"
    state: latest
  loop_control:
    loop_var: item
  loop: # List of packages to install
    - wget
    - curl
    - zsh
    - man
    - tldr
    - bat
    - zoxide
    - fzf
    - gpg
    - micro
